# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getDiscreteStates <- function(stateSelection, stateDuration, patientIDs, patientData, statePriorityVector) {
    .Call(`_Cohort2Trajectory_getDiscreteStates`, stateSelection, stateDuration, patientIDs, patientData, statePriorityVector)
}

removeAfterAbsorbingStatesContinuous <- function(patientData, patientIDs, absorbingStates) {
    .Call(`_Cohort2Trajectory_removeAfterAbsorbingStatesContinuous`, patientData, patientIDs, absorbingStates)
}

removeAfterAbsorbingStatesDiscrete <- function(patientData, patientIDs, absorbingStates) {
    .Call(`_Cohort2Trajectory_removeAfterAbsorbingStatesDiscrete`, patientData, patientIDs, absorbingStates)
}

